apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-spring-boot-gitops-dev
  namespace: demo-project
  labels:
    app: devops-spring-boot-gitops
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-spring-boot-gitops
      env: dev
  template:
    metadata:
      labels:
        app: devops-spring-boot-gitops
        env: dev
    spec:
      containers:
        - name: devops-spring-boot-gitops
          # 这个镜像版本会被 CI 自动更新
          image: 192.168.200.116:30002/ks-devops-harbor/devops-spring-boot-gitops:9
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: VERSION
              value: "1.0"