apiVersion: v1
kind: Service
metadata:
  name: devops-spring-boot-gitops-dev
  namespace: demo-project
  labels:
    app: devops-spring-boot-gitops
    env: dev
spec:
  selector:
    app: devops-spring-boot-gitops
    env: dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP